### ISSUE TITLE
after Save Editing The game starts me all over again :<

### ISSUE THREAD

**Issue by Kikoshi** [supercarotte/PSSE#1]
Hi peeps, using the latest PokemonShuffle, it seems that after i import the edited save, it clears the whole thing and starts me all over.

**Comment by MelonGx** [comment]
Pokemon Shuffle's save seems to tie to your NAND.
You cannot use previous backup / other console's save otherwise it initializes EVEN you did delete the secure value.
You can only backup -> modify -> restore without doing anything else between these 3-step.

@supercarotte Anyone worked in this?

**Comment by supercarotte** [comment]
I don't have any trouble restoring saves and it doesn't seem linked to anything to me. Make sure you aren't using the old "SaveData Manager" in the first place, then try importing a save that's not been edited to see if the problems comes from a bad edit.
