### ISSUE TITLE
Support for skill swaps?

### ISSUE THREAD

**Issue by NinjaBoyLao** [supercarotte/PSSE#2]
Can we put in skill swap items?

**Comment by supercarotte** [comment]
Yes, skill swap is fully supported. You can edit Skill Swapers as any other item in the Items list or with the Bulk Edits options, or you can directly change a pokemon's skill by accessing it from the list. Though for the later, you need resource files that match the latest version of the game or PSSE might not know about multiple skills for that pokemon.

**Comment by NinjaBoyLao** [comment]
thank you sorry i wasnt sure because at the time i didnt have a way of testing it (i was out on my phone)
