### ISSUE TITLE
Pokemon Selection Box only allows a single character

### ISSUE THREAD

**Issue by Icehawk78** [supercarotte/PSSE#3]
If I want to jump down to, say, Gengar, and I type in "Gen" I would expect to be on Genesect and the next g I type in to place me at Gengar.

Instead, currently, if I type "Gen" the cursor will be focused on Natu.

**Comment by supercarotte** [comment]
It has been so since the early releases of PSSE, and it hasn't been fixed because I don't know how to fix it yet. I'm on it though.

**Comment by supercarotte** [comment]
You can now type in the name of a Pokemon to find it thanks to my latest commit. It'll be included in the next release very soon.
