### ISSUE TITLE
New Pokemon introduced in 1.4 update missing.

### ISSUE THREAD

**Issue by TheMCNerd2017** [supercarotte/PSSE#5]
Yesterday or today, Pokemon Shuffle has been updated to Version 1.4.0, which introduces all of the Alolan pokemon, along with more forms for previous Pokemon. The tool does not seem to contain any of the new Pokemon and Formes introduced.

**Comment by jimbo4273** [comment]
You should still be able to mark them as caught, I was able to, just they were all set at level 1

**Comment by TheMCNerd2017** [comment]
The new Pokemon do not appear in the dropdown list of available Pokemon to mark as caught though. Do you mean using the bulk edit tool to mark them as caught?

**Comment by supercarotte** [comment]
Resource files have now been updated to v1.4.8 of the game.
